apiVersion: firewall.linode.upbound.io/v1alpha1
kind: Firewall
metadata:
  annotations:
    meta.upbound.io/example-id: firewall/v1alpha1/firewall
  labels:
    testing.upbound.io/example-name: my_firewall
  name: my-firewall
spec:
  forProvider:
    inbound:
    - action: ACCEPT
      ipv4:
      - 0.0.0.0/0
      ipv6:
      - ::/0
      label: allow-http
      ports: "80"
      protocol: TCP
    - action: ACCEPT
      ipv4:
      - 0.0.0.0/0
      ipv6:
      - ::/0
      label: allow-https
      ports: "443"
      protocol: TCP
    inboundPolicy: DROP
    label: my_firewall
    linodes:
    - ${linode_instance.my_instance.id}
    outbound:
    - action: DROP
      ipv4:
      - 0.0.0.0/0
      ipv6:
      - ::/0
      label: reject-http
      ports: "80"
      protocol: TCP
    - action: DROP
      ipv4:
      - 0.0.0.0/0
      ipv6:
      - ::/0
      label: reject-https
      ports: "443"
      protocol: TCP
    outboundPolicy: ACCEPT

---

