apiVersion: image.linode.upbound.io/v1alpha1
kind: Image
metadata:
  annotations:
    meta.upbound.io/example-id: image/v1alpha1/image
  labels:
    testing.upbound.io/example-name: bar
  name: bar
spec:
  forProvider:
    description: Image taken from foo
    diskId: ${linode_instance.foo.disk.0.id}
    label: foo-sda-image
    linodeId: ${linode_instance.foo.id}

---

apiVersion: instance.linode.upbound.io/v1alpha1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: image/v1alpha1/image
  labels:
    testing.upbound.io/example-name: bar_based
  name: bar-based
spec:
  forProvider:
    image: ${linode_image.bar.id}
    region: eu-west
    type: g6-nanode-1

---

apiVersion: instance.linode.upbound.io/v1alpha1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: image/v1alpha1/image
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    region: us-central
    type: g6-nanode-1

---

